version: '3.9'

services:
  # --- Apache + PHP ---
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: symfony_app
    restart: unless-stopped
    volumes:
      - ./symfony:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  # --- MySQL ---
  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # --- PhpMyAdmin ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
